config/routes.rb
Rails.application.routes.draw do
  root "accounts#index"

  devise_for :users
  resources :accounts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :accounts
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update]

  def index
    @accounts = current_user.accounts
  end

  def show
  end

  def new
    @account = Account.new
  end

  def create
    @account = current_user.accounts.new(account_params)
    if @account.save
      redirect_to accounts_path
    else
      render :new
    end
  end

  def edit
    @account = Account.find(params[:id])
  end

  def update
    @account = Account.find(params[:id])

    if @account.update(account_params)
      redirect_to accounts_path
    else
      render :edit
    end
  end

  def destroy
    Account.find(params[:id]).destroy
    redirect_to accounts_path
  end



  private
    def account_params
      params.require(:account).permit(:name, :note)
    end

    # don't just find by the Account model or you may potentially be able to view other users accounts
    def set_account
      @account = current_user.accounts.find(params[:id])
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def update
    @account = Account.find(params[:id])
  
    if @account.update(account_params)
      redirect_to account_path
    else
      render :edit
    end
  end

  def edit
    @account = Account.find(params[:id])
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/accounts/edit.html.erb
<h1>Edit Note</h1>
<%= form_for @account do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :note %>
  <%= f.text_field :note %>

  <%= f.submit %>
<% end %>

app/views/accounts/index.html.erb
<%= button_to "Log Out", destroy_user_session_path, method: :delete %>
<h2>Welcome <%= current_user.first_name %></h2>

<hr />
<%= link_to "Add Note", new_account_path %>
<h3>Your Notes</h3>
<ul>
  <% @accounts.each do |account| %>
    <li>
      <%= account.name %>: <%= account.note %> | <%= link_to 'Edit', edit_account_path(account) %> | <%= link_to 'Delete', account, method: :delete %> |
    </li>
  <% end %>
</ul>

app/views/accounts/new.html.erb
<h1>New Note</h1>
<%= form_with(model: @account, local: true) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Name" %>
  </div>
  <div class="field">
    <%= f.label :note %>
    <%= f.text_field :note %>
  </div>
  <%= f.submit %>
<% end %>

app/views/accounts/show.html.erb
<h1>Accounts#show</h1>
<p>Find me in app/views/accounts/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseProject1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/notes/edit.html.erb
<h1>Edit Page</h1>
<%= form_for @account do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :note %>
  <%= f.text_area :note %>

  <%= f.submit %>
<% end %>

app/views/notes/index.html.erb
<%= link_to 'Edit note', edit_account_path(account) %>

app/views/notes/new.html.erb
<h1>Notes#new</h1>
<p>Find me in app/views/notes/new.html.erb</p>

app/views/notes/show.html.erb
<h1>Notes#show</h1>
<p>Find me in app/views/notes/show.html.erb</p>